#!/usr/bin/env python3
"""Export expert-validated scans as a YOLO-format training dataset.

This closes the learning loop: scans that an expert **confirmed** (optionally
with a corrected class) become positive training samples; scans the expert
**rejected** become negative background samples (copied without labels).

Example:
    python scripts/export_training.py --out data/expert_dataset
    python scripts/train.py --data data/expert_dataset/data.yaml --epochs 50

Only located context and verdicts live in the DB; the images and boxes come
from the scans themselves.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, default=ROOT / "data" / "expert_dataset")
    p.add_argument(
        "--db-url",
        default=None,
        help="Override DATABASE_URL (defaults to the project's .env / default).",
    )
    p.add_argument(
        "--min-boxes",
        type=int,
        default=1,
        help="Minimum number of boxes a confirmed scan must have to be exported.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    if args.db_url:
        import os

        os.environ["DATABASE_URL"] = args.db_url

    from app.database import SessionLocal
    from app.models import ExpertReview, Scan

    db = SessionLocal()
    try:
        scans = db.query(Scan).all()
        verdict_by_scan: dict[int, str] = {}
        correction_by_scan: dict[int, str | None] = {}
        for review in db.query(ExpertReview).filter(ExpertReview.scan_id.isnot(None)).all():
            # Latest verdict wins.
            verdict_by_scan[review.scan_id] = review.verdict
            correction_by_scan[review.scan_id] = review.corrected_class

        confirmed = [s for s in scans if verdict_by_scan.get(s.id) == "confirmed"]
        rejected = [s for s in scans if verdict_by_scan.get(s.id) == "rejected"]
    finally:
        db.close()

    if not confirmed and not rejected:
        sys.exit(
            "No expert reviews found yet. Use POST /api/reviews to confirm or "
            "reject scans, then re-run this export."
        )

    images_dir = args.out / "images"
    labels_dir = args.out / "labels"
    for d in (images_dir, labels_dir):
        d.mkdir(parents=True, exist_ok=True)

    def resolve(rel: str) -> Path:
        path = Path(rel)
        return path if path.is_absolute() else ROOT / path

    class_ids: dict[str, int] = {}
    exported_pos = 0
    exported_neg = 0

    for scan in confirmed:
        boxes = []
        for det in scan.detections:
            name = correction_by_scan.get(scan.id) or det.class_name
            if name not in class_ids:
                class_ids[name] = len(class_ids)
            cx = (det.bbox_x + det.bbox_w / 2) / max(scan.image_width, 1)
            cy = (det.bbox_y + det.bbox_h / 2) / max(scan.image_height, 1)
            bw = det.bbox_w / max(scan.image_width, 1)
            bh = det.bbox_h / max(scan.image_height, 1)
            boxes.append((class_ids[name], cx, cy, bw, bh))

        if len(boxes) < args.min_boxes:
            continue

        src = resolve(scan.image_path)
        if not src.is_file():
            print(f"  [skip] scan #{scan.id}: image missing at {src}")
            continue

        stem = f"scan{scan.id:06d}"
        shutil.copyfile(src, images_dir / f"{stem}{src.suffix.lower()}")
        with open(labels_dir / f"{stem}.txt", "w", encoding="utf-8") as fh:
            for cid, cx, cy, bw, bh in boxes:
                fh.write(f"{cid} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}\n")
        exported_pos += 1

    for scan in rejected:
        src = resolve(scan.image_path)
        if not src.is_file():
            continue
        stem = f"scan{scan.id:06d}"
        shutil.copyfile(src, images_dir / f"{stem}{src.suffix.lower()}")
        (labels_dir / f"{stem}.txt").touch()  # empty label = background image
        exported_neg += 1

    names_list = [name for name, _ in sorted(class_ids.items(), key=lambda kv: kv[1])]
    with open(args.out / "data.yaml", "w", encoding="utf-8") as fh:
        fh.write(f"# Auto-generated by scripts/export_training.py\n")
        fh.write(f"path: {args.out.resolve().as_posix()}\n")
        fh.write("train: images\nval: images\n")
        fh.write(f"nc: {len(names_list)}\n")
        fh.write("names:\n")
        for name in names_list:
            fh.write(f"  - {name}\n")

    print(f"Confirmed scans exported : {exported_pos}")
    print(f"Rejected (background)    : {exported_neg}")
    print(f"Classes                  : {names_list or '(none)'}")
    print(f"Dataset written to       : {args.out}")
    if exported_pos:
        print(
            "\nNext step:\n"
            f"  python scripts/train.py --data {args.out / 'data.yaml'} "
            "--model yolov8n.pt --epochs 50"
        )


if __name__ == "__main__":
    main()
